// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qrdvyehgegvyyiuebxix.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFyZHZ5ZWhnZWd2eXlpdWVieGl4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDA2MzE3MDYsImV4cCI6MjA1NjIwNzcwNn0.13MXAbFVumiNvgTNr6kWY7z2g6Pf4MUBIDnN0z3eR98";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);